---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: cluster
    groups:
      - k8s
provisioner:
  name: ansible
  lint: |
    set -e
    ansible-lint
  config_options:
    defaults:
      verbosity: 1
  inventory:
    hosts:
      longhorn_executor:
        hosts:
          longhorn-test-control-plane: {}
      longhorn_nodes:
        hosts:
          longhorn-test-control-plane: {}
      all:
        hosts:
          localhost:
            kubeconfig: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
