---
- name: Verify
  hosts: longhorn-test-control-plane
  connection: docker
  gather_facts: false
  tasks:
    - name: Check executor dependencies
      ansible.builtin.apt:
        name:
          - gpg
          - apt-transport-https
          - python3-pip
        state: present
      check_mode: true
      register: longhorn_verify
      failed_when: longhorn_verify.changed

    - name: Check ansible dependencies
      ansible.builtin.pip:
        name:
          - kubernetes
          - openshift
          - pyyaml
      check_mode: true
      register: longhorn_verify
      failed_when: longhorn_verify.changed

    - name: Check helm key
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present
      check_mode: true
      register: longhorn_verify
      failed_when: longhorn_verify.changed

    - name: Check helm repo
      ansible.builtin.apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present
      check_mode: true
      register: longhorn_verify
      failed_when: longhorn_verify.changed

    - name: Check helm
      ansible.builtin.apt:
        name:
          - helm
        state: present
      check_mode: true
      register: longhorn_verify
      failed_when: longhorn_verify.changed

    - name: Check longhorn dependencies
      ansible.builtin.apt:
        name:
          - open-iscsi
          - curl
          - util-linux
          - grep
          - mawk
          - libblkid1
        state: present
      check_mode: true
      register: longhorn_verify
      failed_when: longhorn_verify.changed

    - name: Check longhorn chart repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"
      check_mode: true
      register: longhorn_verify
      failed_when: longhorn_verify.changed

    - name: Check longhorn chart
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: true
        update_repo_cache: true
      run_once: true
      check_mode: true
      register: longhorn_verify
      failed_when: longhorn_verify.changed
...
